const vm=require('node:vm'),fs=require('node:fs'),assert=require('node:assert/strict');
class Element {constructor(){this.value='';this.hidden=false;this.disabled=false;this.textContent='';this.children=[]}append(x){this.children.push(x)}replaceChildren(...xs){this.children=xs}setAttribute(){}addEventListener(){}focus(){}}
class Events {constructor(){this.handlers={}}on(k,f){(this.handlers[k]??=[]).push(f)}emit(k,x){for(const f of this.handlers[k]||[])f(x)}}
const nodes={},el=id=>nodes[id]??=new Element();el('game').hidden=true;
let timer=0;const ctx={console,URL,Date,Map,Uint8Array,crypto:require('node:crypto').webcrypto,setTimeout:()=>++timer,clearTimeout(){},setInterval(){},navigator:{},location:{hash:'',origin:'https://example.com',href:'https://example.com/'},document:{getElementById:el,createElement:()=>new Element(),head:new Element(),addEventListener(){},visibilityState:'visible'},Peer:class extends Events {constructor(){super();ctx.peerMock=this}destroy(){}reconnect(){}}};ctx.window=ctx;vm.createContext(ctx);vm.runInContext(fs.readFileSync(__dirname+'/index.html','utf8').match(/<script>([\s\S]*)<\/script>/)[1],ctx);
const run=s=>vm.runInContext(s,ctx);function player(id,name){const c=new Events();c.peer=id;c.open=true;c.send=()=>{};c.close=()=>c.emit('close');ctx.peerMock.emit('connection',c);c.emit('data',{type:'hello',name});return c}
el('host').onclick();ctx.peerMock.emit('open');const a=player('a','Quinn'),b=player('b','Conner');el('reset').onclick();a.emit('data',{type:'buzz',round:1});b.emit('data',{type:'buzz',round:1});assert.equal(el('result').textContent,'Quinn is first!');el('players').children.find(x=>x.children[0].textContent.startsWith('Quinn')).children[2].onclick();
run(`videoReady=true;videoPlayer={time:0,mode:1,getDuration(){return 180},getCurrentTime(){return this.time},getPlayerState(){return this.mode},seekTo(t){this.time=t},playVideo(){this.mode=1},pauseVideo(){this.mode=2},destroy(){}}`);
el('timingMode').value='timestamps';el('questionTimes').value='0:10\n0:40\n1:10';el('answerWindow').value='20';el('startAuto').onclick();assert.equal(run('state.open'),false);run('videoPlayer.time=10;syncVideo()');assert.equal(run('state.question'),1);assert.equal(run('state.open'),true);let round=run('state.round');a.emit('data',{type:'buzz',round});b.emit('data',{type:'buzz',round});assert.equal(run('state.winner.name'),'Quinn');run('syncVideo()');assert.equal(run('state.open'),false);run('videoPlayer.time=40;syncVideo()');assert.equal(run('state.question'),2);assert.equal(run('state.open'),true);a.emit('data',{type:'buzz',round});assert.equal(run('state.winner'),null);run('videoPlayer.mode=2;syncVideo()');assert.equal(run('state.open'),false);run('videoPlayer.mode=1;syncVideo()');assert.equal(run('state.open'),true);run('videoPlayer.time=60;syncVideo()');assert.equal(run('state.open'),false);run('videoPlayer.time=12;syncVideo()');assert.equal(run('state.question'),1);assert.equal(run('state.open'),true);assert.equal(run("scores.get('quinn').score"),1);ctx.document.visibilityState='hidden';run('syncVideo()');assert.equal(run('state.open'),false);ctx.document.visibilityState='visible';run('syncVideo()');assert.equal(run('state.open'),true);
el('pauseOnBuzz').checked=true;a.emit('data',{type:'buzz',round:run('state.round')});assert.equal(run('videoPlayer.mode'),2);run('videoPlayer.time=180;videoPlayer.mode=0;syncVideo()');assert.equal(run('state.open'),false);el('stopAuto').onclick();el('reset').onclick();assert.equal(run('state.open'),true);assert.equal(run('state.video'),false);
assert.equal(run("youtubeId('https://youtu.be/dQw4w9WgXcQ?t=3')"),'dQw4w9WgXcQ');assert.equal(run("youtubeId('https://evil.com/watch?v=dQw4w9WgXcQ')"),null);assert.equal(run("parseTime('1:02:03')"),3723);assert.throws(()=>run("parseTime('1:99')"));el('questionTimes').value='0:40\n0:10';assert.throws(()=>run('buildSchedule()'));el('questionTimes').value='3:01';assert.throws(()=>run('buildSchedule()'));el('timingMode').value='interval';el('firstTime').value='0:10';el('intervalTime').value='30';el('questionCount').value='3';assert.equal(run('JSON.stringify(buildSchedule().times)'),'[10,40,70]');
el('leave').onclick();assert.equal(run('autoQuiz'),null);console.log('PASS: manual buzz + scoring, exact and interval scheduling, pause/resume, question transitions, stale buzz rejection, rewind, score retention, hidden-tab lock, pause-on-buzz, video end, manual fallback, URL/time validation, cleanup. DOM and video/peer transports mocked.');
